name: End-to-End Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    services:
      # Start Postgres container for testing
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Needed so that PostgreSQL is ready before we run our tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend
      
      - name: Run tests
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/testdb
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret
          ADMIN_EMAIL: admin@example.com
          ADMIN_PASSWORD: admin123
        run: npx playwright test
        working-directory: frontend
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
